# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/dialogmainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from es_common.utils.qt import QtCore, QtGui, QtWidgets

from block_manager.view import resources_rc


class Ui_DialogGUI(object):
    def setupUi(self, DialogGUI):
        DialogGUI.setObjectName("DialogGUI")
        DialogGUI.resize(1216, 828)
        DialogGUI.setAutoFillBackground(True)
        self.centralWidget = QtWidgets.QWidget(DialogGUI)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout_5.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_5.setSpacing(6)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_8 = QtWidgets.QLabel(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_5.addWidget(self.label_8, 0, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.centralWidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_5.addWidget(self.line, 1, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.designPanelLayout = QtWidgets.QGridLayout()
        self.designPanelLayout.setSpacing(6)
        self.designPanelLayout.setObjectName("designPanelLayout")
        self.tmpWidget = QtWidgets.QWidget(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tmpWidget.sizePolicy().hasHeightForWidth())
        self.tmpWidget.setSizePolicy(sizePolicy)
        self.tmpWidget.setObjectName("tmpWidget")
        self.designPanelLayout.addWidget(self.tmpWidget, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.designPanelLayout, 0, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_2, 2, 0, 1, 1)
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setSpacing(6)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setSpacing(6)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.clearDropListButton = QtWidgets.QPushButton(self.centralWidget)
        self.clearDropListButton.setObjectName("clearDropListButton")
        self.gridLayout_9.addWidget(self.clearDropListButton, 0, 1, 1, 1)
        self.deleteDropListItemsButton = QtWidgets.QPushButton(self.centralWidget)
        self.deleteDropListItemsButton.setEnabled(False)
        self.deleteDropListItemsButton.setObjectName("deleteDropListItemsButton")
        self.gridLayout_9.addWidget(self.deleteDropListItemsButton, 0, 0, 1, 1)
        self.saveDropListButton = QtWidgets.QPushButton(self.centralWidget)
        self.saveDropListButton.setObjectName("saveDropListButton")
        self.gridLayout_9.addWidget(self.saveDropListButton, 0, 2, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout_9, 0, 0, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.centralWidget)
        self.label_21.setText("")
        self.label_21.setObjectName("label_21")
        self.gridLayout_10.addWidget(self.label_21, 0, 1, 1, 1)
        self.newBlockPushButton = QtWidgets.QPushButton(self.centralWidget)
        self.newBlockPushButton.setObjectName("newBlockPushButton")
        self.gridLayout_10.addWidget(self.newBlockPushButton, 0, 2, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_10, 3, 0, 1, 1)
        self.line_4 = QtWidgets.QFrame(self.centralWidget)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout_5.addWidget(self.line_4, 4, 0, 1, 1)
        self.gridLayout_11 = QtWidgets.QGridLayout()
        self.gridLayout_11.setSpacing(6)
        self.gridLayout_11.setObjectName("gridLayout_11")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem, 0, 0, 1, 1)
        self.enableMovingCheckBox = QtWidgets.QCheckBox(self.centralWidget)
        self.enableMovingCheckBox.setObjectName("enableMovingCheckBox")
        self.gridLayout_11.addWidget(self.enableMovingCheckBox, 0, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.centralWidget)
        self.label.setEnabled(False)
        self.label.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout_11.addWidget(self.label, 0, 4, 1, 1)
        self.line_6 = QtWidgets.QFrame(self.centralWidget)
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.gridLayout_11.addWidget(self.line_6, 0, 3, 1, 1)
        self.line_5 = QtWidgets.QFrame(self.centralWidget)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout_11.addWidget(self.line_5, 1, 0, 1, 6)
        self.enagementRepetitionsSpinBox = QtWidgets.QSpinBox(self.centralWidget)
        self.enagementRepetitionsSpinBox.setEnabled(False)
        self.enagementRepetitionsSpinBox.setMinimum(1)
        self.enagementRepetitionsSpinBox.setObjectName("enagementRepetitionsSpinBox")
        self.gridLayout_11.addWidget(self.enagementRepetitionsSpinBox, 0, 5, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.centralWidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_11.addWidget(self.line_2, 0, 1, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_11, 5, 0, 1, 1)
        DialogGUI.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(DialogGUI)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1216, 22))
        self.menuBar.setObjectName("menuBar")
        DialogGUI.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(DialogGUI)
        self.mainToolBar.setEnabled(True)
        self.mainToolBar.setAllowedAreas(QtCore.Qt.AllToolBarAreas)
        self.mainToolBar.setOrientation(QtCore.Qt.Horizontal)
        self.mainToolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.mainToolBar.setObjectName("mainToolBar")
        DialogGUI.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(DialogGUI)
        self.statusBar.setObjectName("statusBar")
        DialogGUI.setStatusBar(self.statusBar)
        self.behavioralParametersDockWidget = QtWidgets.QDockWidget(DialogGUI)
        self.behavioralParametersDockWidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.behavioralParametersDockWidget.sizePolicy().hasHeightForWidth())
        self.behavioralParametersDockWidget.setSizePolicy(sizePolicy)
        self.behavioralParametersDockWidget.setMinimumSize(QtCore.QSize(340, 400))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.behavioralParametersDockWidget.setFont(font)
        self.behavioralParametersDockWidget.setFeatures(QtWidgets.QDockWidget.AllDockWidgetFeatures)
        self.behavioralParametersDockWidget.setObjectName("behavioralParametersDockWidget")
        self.dockWidgetContents_22 = QtWidgets.QWidget()
        self.dockWidgetContents_22.setObjectName("dockWidgetContents_22")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.dockWidgetContents_22)
        self.gridLayout_18.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_18.setSpacing(6)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.scrollArea = QtWidgets.QScrollArea(self.dockWidgetContents_22)
        self.scrollArea.setEnabled(True)
        self.scrollArea.setAutoFillBackground(True)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.Box)
        self.scrollArea.setFrameShadow(QtWidgets.QFrame.Raised)
        self.scrollArea.setLineWidth(1)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 369, 800))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_17.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_17.setSpacing(6)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.gridLayout_36 = QtWidgets.QGridLayout()
        self.gridLayout_36.setSpacing(6)
        self.gridLayout_36.setObjectName("gridLayout_36")
        self.groupBox_6 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_6.setFont(font)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_24 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_24.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_24.setSpacing(6)
        self.gridLayout_24.setObjectName("gridLayout_24")
        self.gridLayout_23 = QtWidgets.QGridLayout()
        self.gridLayout_23.setSpacing(6)
        self.gridLayout_23.setObjectName("gridLayout_23")
        self.label_19 = QtWidgets.QLabel(self.groupBox_6)
        self.label_19.setObjectName("label_19")
        self.gridLayout_23.addWidget(self.label_19, 3, 4, 1, 1)
        self.voiceProsodySlider = QtWidgets.QSlider(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.voiceProsodySlider.sizePolicy().hasHeightForWidth())
        self.voiceProsodySlider.setSizePolicy(sizePolicy)
        self.voiceProsodySlider.setMinimum(0)
        self.voiceProsodySlider.setMaximum(1)
        self.voiceProsodySlider.setSingleStep(1)
        self.voiceProsodySlider.setPageStep(1)
        self.voiceProsodySlider.setProperty("value", 0)
        self.voiceProsodySlider.setOrientation(QtCore.Qt.Horizontal)
        self.voiceProsodySlider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.voiceProsodySlider.setTickInterval(1)
        self.voiceProsodySlider.setObjectName("voiceProsodySlider")
        self.gridLayout_23.addWidget(self.voiceProsodySlider, 5, 2, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.groupBox_6)
        self.label_18.setObjectName("label_18")
        self.gridLayout_23.addWidget(self.label_18, 3, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_6)
        self.label_6.setObjectName("label_6")
        self.gridLayout_23.addWidget(self.label_6, 1, 4, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.groupBox_6)
        self.label_14.setObjectName("label_14")
        self.gridLayout_23.addWidget(self.label_14, 1, 0, 1, 1)
        self.voiceSpeedSlider = QtWidgets.QSlider(self.groupBox_6)
        self.voiceSpeedSlider.setMinimum(-4)
        self.voiceSpeedSlider.setMaximum(4)
        self.voiceSpeedSlider.setPageStep(1)
        self.voiceSpeedSlider.setOrientation(QtCore.Qt.Horizontal)
        self.voiceSpeedSlider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.voiceSpeedSlider.setTickInterval(2)
        self.voiceSpeedSlider.setObjectName("voiceSpeedSlider")
        self.gridLayout_23.addWidget(self.voiceSpeedSlider, 3, 1, 1, 3)
        self.voiceSpeedLabel = QtWidgets.QLabel(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.voiceSpeedLabel.sizePolicy().hasHeightForWidth())
        self.voiceSpeedLabel.setSizePolicy(sizePolicy)
        self.voiceSpeedLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.voiceSpeedLabel.setObjectName("voiceSpeedLabel")
        self.gridLayout_23.addWidget(self.voiceSpeedLabel, 2, 1, 1, 3)
        self.voicePitchSlider = QtWidgets.QSlider(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.voicePitchSlider.sizePolicy().hasHeightForWidth())
        self.voicePitchSlider.setSizePolicy(sizePolicy)
        self.voicePitchSlider.setMinimum(-4)
        self.voicePitchSlider.setMaximum(4)
        self.voicePitchSlider.setSingleStep(1)
        self.voicePitchSlider.setPageStep(1)
        self.voicePitchSlider.setProperty("value", 0)
        self.voicePitchSlider.setOrientation(QtCore.Qt.Horizontal)
        self.voicePitchSlider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.voicePitchSlider.setTickInterval(2)
        self.voicePitchSlider.setObjectName("voicePitchSlider")
        self.gridLayout_23.addWidget(self.voicePitchSlider, 1, 1, 1, 3)
        self.voicePitchLabel = QtWidgets.QLabel(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.voicePitchLabel.sizePolicy().hasHeightForWidth())
        self.voicePitchLabel.setSizePolicy(sizePolicy)
        self.voicePitchLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.voicePitchLabel.setObjectName("voicePitchLabel")
        self.gridLayout_23.addWidget(self.voicePitchLabel, 0, 1, 1, 3)
        self.label_15 = QtWidgets.QLabel(self.groupBox_6)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout_23.addWidget(self.label_15, 4, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_23.addItem(spacerItem1, 4, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_23.addItem(spacerItem2, 4, 3, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.groupBox_6)
        self.label_16.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_16.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout_23.addWidget(self.label_16, 5, 0, 1, 2)
        self.label_17 = QtWidgets.QLabel(self.groupBox_6)
        self.label_17.setObjectName("label_17")
        self.gridLayout_23.addWidget(self.label_17, 5, 3, 1, 2)
        self.gridLayout_24.addLayout(self.gridLayout_23, 0, 0, 1, 1)
        self.gridLayout_36.addWidget(self.groupBox_6, 3, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.behavioralParametersApplyToAllButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.behavioralParametersApplyToAllButton.setObjectName("behavioralParametersApplyToAllButton")
        self.gridLayout.addWidget(self.behavioralParametersApplyToAllButton, 1, 1, 1, 1)
        self.behavioralParametersApplyComboBox = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.behavioralParametersApplyComboBox.setObjectName("behavioralParametersApplyComboBox")
        self.behavioralParametersApplyComboBox.addItem("")
        self.behavioralParametersApplyComboBox.addItem("")
        self.behavioralParametersApplyComboBox.addItem("")
        self.behavioralParametersApplyComboBox.addItem("")
        self.behavioralParametersApplyComboBox.addItem("")
        self.behavioralParametersApplyComboBox.addItem("")
        self.gridLayout.addWidget(self.behavioralParametersApplyComboBox, 0, 0, 1, 2)
        self.behavioralParametersApplyToItemsBelowButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.behavioralParametersApplyToItemsBelowButton.setObjectName("behavioralParametersApplyToItemsBelowButton")
        self.gridLayout.addWidget(self.behavioralParametersApplyToItemsBelowButton, 1, 0, 1, 1)
        self.gridLayout_36.addLayout(self.gridLayout, 7, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_36.addItem(spacerItem3, 8, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_6.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_6.setSpacing(6)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setSpacing(6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.greenEyeColorRadioButton = QtWidgets.QRadioButton(self.groupBox)
        self.greenEyeColorRadioButton.setObjectName("greenEyeColorRadioButton")
        self.buttonGroup = QtWidgets.QButtonGroup(DialogGUI)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.greenEyeColorRadioButton)
        self.gridLayout_4.addWidget(self.greenEyeColorRadioButton, 1, 0, 1, 1)
        self.blueEyeColorRadioButton = QtWidgets.QRadioButton(self.groupBox)
        self.blueEyeColorRadioButton.setObjectName("blueEyeColorRadioButton")
        self.buttonGroup.addButton(self.blueEyeColorRadioButton)
        self.gridLayout_4.addWidget(self.blueEyeColorRadioButton, 1, 1, 1, 1)
        self.redEyeColorRadioButton = QtWidgets.QRadioButton(self.groupBox)
        self.redEyeColorRadioButton.setObjectName("redEyeColorRadioButton")
        self.buttonGroup.addButton(self.redEyeColorRadioButton)
        self.gridLayout_4.addWidget(self.redEyeColorRadioButton, 0, 1, 1, 1)
        self.whiteEyeColorRadioButton = QtWidgets.QRadioButton(self.groupBox)
        self.whiteEyeColorRadioButton.setChecked(True)
        self.whiteEyeColorRadioButton.setObjectName("whiteEyeColorRadioButton")
        self.buttonGroup.addButton(self.whiteEyeColorRadioButton)
        self.gridLayout_4.addWidget(self.whiteEyeColorRadioButton, 0, 0, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        self.gridLayout_36.addWidget(self.groupBox, 4, 0, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_20 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_20.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_20.setSpacing(6)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.gridLayout_19 = QtWidgets.QGridLayout()
        self.gridLayout_19.setSpacing(6)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.label_12 = QtWidgets.QLabel(self.groupBox_4)
        self.label_12.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout_19.addWidget(self.label_12, 0, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox_4)
        self.label_13.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout_19.addWidget(self.label_13, 0, 3, 1, 1)
        self.gazePatternSlider = QtWidgets.QSlider(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gazePatternSlider.sizePolicy().hasHeightForWidth())
        self.gazePatternSlider.setSizePolicy(sizePolicy)
        self.gazePatternSlider.setMaximum(1)
        self.gazePatternSlider.setPageStep(1)
        self.gazePatternSlider.setProperty("value", 0)
        self.gazePatternSlider.setSliderPosition(0)
        self.gazePatternSlider.setOrientation(QtCore.Qt.Horizontal)
        self.gazePatternSlider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.gazePatternSlider.setObjectName("gazePatternSlider")
        self.gridLayout_19.addWidget(self.gazePatternSlider, 0, 2, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_19.addItem(spacerItem4, 0, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_19.addItem(spacerItem5, 0, 4, 1, 1)
        self.gridLayout_20.addLayout(self.gridLayout_19, 0, 0, 1, 1)
        self.gridLayout_36.addWidget(self.groupBox_4, 1, 0, 1, 1)
        self.groupBox_7 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_7.setFont(font)
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_26 = QtWidgets.QGridLayout(self.groupBox_7)
        self.gridLayout_26.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_26.setSpacing(6)
        self.gridLayout_26.setObjectName("gridLayout_26")
        self.gridLayout_25 = QtWidgets.QGridLayout()
        self.gridLayout_25.setSpacing(6)
        self.gridLayout_25.setObjectName("gridLayout_25")
        self.label_4 = QtWidgets.QLabel(self.groupBox_7)
        self.label_4.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_25.addWidget(self.label_4, 0, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_7)
        self.label_3.setObjectName("label_3")
        self.gridLayout_25.addWidget(self.label_3, 0, 0, 1, 1)
        self.proxemicsSlider = QtWidgets.QSlider(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.proxemicsSlider.sizePolicy().hasHeightForWidth())
        self.proxemicsSlider.setSizePolicy(sizePolicy)
        self.proxemicsSlider.setMinimum(0)
        self.proxemicsSlider.setMaximum(10)
        self.proxemicsSlider.setPageStep(1)
        self.proxemicsSlider.setProperty("value", 5)
        self.proxemicsSlider.setSliderPosition(5)
        self.proxemicsSlider.setOrientation(QtCore.Qt.Horizontal)
        self.proxemicsSlider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.proxemicsSlider.setTickInterval(2)
        self.proxemicsSlider.setObjectName("proxemicsSlider")
        self.gridLayout_25.addWidget(self.proxemicsSlider, 0, 1, 1, 1)
        self.proxemicsLcdNumber = QtWidgets.QLCDNumber(self.groupBox_7)
        self.proxemicsLcdNumber.setEnabled(True)
        self.proxemicsLcdNumber.setAutoFillBackground(False)
        self.proxemicsLcdNumber.setStyleSheet("background-color: rgb(204, 204, 204);")
        self.proxemicsLcdNumber.setFrameShape(QtWidgets.QFrame.Panel)
        self.proxemicsLcdNumber.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.proxemicsLcdNumber.setLineWidth(1)
        self.proxemicsLcdNumber.setSmallDecimalPoint(True)
        self.proxemicsLcdNumber.setProperty("value", 3.5)
        self.proxemicsLcdNumber.setObjectName("proxemicsLcdNumber")
        self.gridLayout_25.addWidget(self.proxemicsLcdNumber, 1, 1, 1, 1)
        self.gridLayout_26.addLayout(self.gridLayout_25, 0, 0, 1, 1)
        self.gridLayout_36.addWidget(self.groupBox_7, 2, 0, 1, 1)
        self.gridLayout_28 = QtWidgets.QGridLayout()
        self.gridLayout_28.setSpacing(6)
        self.gridLayout_28.setObjectName("gridLayout_28")
        self.testBehavioralParametersButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.testBehavioralParametersButton.setEnabled(False)
        self.testBehavioralParametersButton.setObjectName("testBehavioralParametersButton")
        self.gridLayout_28.addWidget(self.testBehavioralParametersButton, 1, 0, 1, 1)
        self.behavioralParametersApplyButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.behavioralParametersApplyButton.setObjectName("behavioralParametersApplyButton")
        self.gridLayout_28.addWidget(self.behavioralParametersApplyButton, 1, 1, 1, 1)
        self.warningLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setItalic(True)
        self.warningLabel.setFont(font)
        self.warningLabel.setStyleSheet("color: rgb(236, 236, 236);")
        self.warningLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.warningLabel.setObjectName("warningLabel")
        self.gridLayout_28.addWidget(self.warningLabel, 0, 0, 1, 2)
        self.gridLayout_36.addLayout(self.gridLayout_28, 5, 0, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_22 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_22.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_22.setSpacing(6)
        self.gridLayout_22.setObjectName("gridLayout_22")
        self.gridLayout_21 = QtWidgets.QGridLayout()
        self.gridLayout_21.setSpacing(6)
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.label_2 = QtWidgets.QLabel(self.groupBox_5)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_21.addWidget(self.label_2, 0, 3, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_21.addItem(spacerItem6, 0, 0, 1, 1)
        self.gestureOpennessSlider = QtWidgets.QSlider(self.groupBox_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gestureOpennessSlider.sizePolicy().hasHeightForWidth())
        self.gestureOpennessSlider.setSizePolicy(sizePolicy)
        self.gestureOpennessSlider.setMinimum(0)
        self.gestureOpennessSlider.setMaximum(1)
        self.gestureOpennessSlider.setPageStep(1)
        self.gestureOpennessSlider.setProperty("value", 0)
        self.gestureOpennessSlider.setOrientation(QtCore.Qt.Horizontal)
        self.gestureOpennessSlider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.gestureOpennessSlider.setObjectName("gestureOpennessSlider")
        self.gridLayout_21.addWidget(self.gestureOpennessSlider, 0, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_5)
        self.label_10.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_21.addWidget(self.label_10, 0, 1, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_21.addItem(spacerItem7, 0, 4, 1, 1)
        self.gridLayout_22.addLayout(self.gridLayout_21, 0, 0, 1, 1)
        self.gridLayout_36.addWidget(self.groupBox_5, 0, 0, 1, 1)
        self.line_7 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.gridLayout_36.addWidget(self.line_7, 6, 0, 1, 1)
        self.gridLayout_17.addLayout(self.gridLayout_36, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_18.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.behavioralParametersDockWidget.setWidget(self.dockWidgetContents_22)
        DialogGUI.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.behavioralParametersDockWidget)
        self.blocksDockWidget = QtWidgets.QDockWidget(DialogGUI)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.blocksDockWidget.setFont(font)
        self.blocksDockWidget.setFeatures(
            QtWidgets.QDockWidget.DockWidgetFloatable | QtWidgets.QDockWidget.DockWidgetMovable)
        self.blocksDockWidget.setObjectName("blocksDockWidget")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.dockWidgetContents)
        self.gridLayout_8.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_8.setSpacing(6)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.groupBox_11 = QtWidgets.QGroupBox(self.dockWidgetContents)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_11.setFont(font)
        self.groupBox_11.setTitle("")
        self.groupBox_11.setObjectName("groupBox_11")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_11)
        self.gridLayout_7.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_7.setSpacing(6)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.line_3 = QtWidgets.QFrame(self.groupBox_11)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_7.addWidget(self.line_3, 1, 0, 1, 1)
        self.dragListWidget = QtWidgets.QListWidget(self.groupBox_11)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.dragListWidget.setFont(font)
        self.dragListWidget.setLineWidth(1)
        self.dragListWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.dragListWidget.setDragEnabled(True)
        self.dragListWidget.setDragDropMode(QtWidgets.QAbstractItemView.DragOnly)
        self.dragListWidget.setAlternatingRowColors(True)
        self.dragListWidget.setIconSize(QtCore.QSize(100, 60))
        self.dragListWidget.setWordWrap(True)
        self.dragListWidget.setSelectionRectVisible(True)
        self.dragListWidget.setObjectName("dragListWidget")
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/hreresources/pepper-icons/pepper-greet.png"), QtGui.QIcon.Normal,
                       QtGui.QIcon.Off)
        item.setIcon(icon)
        self.dragListWidget.addItem(item)
        self.gridLayout_7.addWidget(self.dragListWidget, 2, 0, 1, 1)
        self.dialogueBlocksCategoryComboBox = QtWidgets.QComboBox(self.groupBox_11)
        self.dialogueBlocksCategoryComboBox.setObjectName("dialogueBlocksCategoryComboBox")
        self.dialogueBlocksCategoryComboBox.addItem("")
        self.dialogueBlocksCategoryComboBox.addItem("")
        self.dialogueBlocksCategoryComboBox.addItem("")
        self.dialogueBlocksCategoryComboBox.addItem("")
        self.dialogueBlocksCategoryComboBox.addItem("")
        self.gridLayout_7.addWidget(self.dialogueBlocksCategoryComboBox, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_11, 0, 0, 1, 2)
        self.gridLayout_8.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.blocksDockWidget.setWidget(self.dockWidgetContents)
        DialogGUI.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.blocksDockWidget)
        self.dockWidget = QtWidgets.QDockWidget(DialogGUI)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidget.sizePolicy().hasHeightForWidth())
        self.dockWidget.setSizePolicy(sizePolicy)
        self.dockWidget.setMinimumSize(QtCore.QSize(98, 150))
        self.dockWidget.setFloating(False)
        self.dockWidget.setFeatures(QtWidgets.QDockWidget.AllDockWidgetFeatures)
        self.dockWidget.setAllowedAreas(QtCore.Qt.AllDockWidgetAreas)
        self.dockWidget.setObjectName("dockWidget")
        self.dockWidgetContents_2 = QtWidgets.QWidget()
        self.dockWidgetContents_2.setObjectName("dockWidgetContents_2")
        self.gridLayout_27 = QtWidgets.QGridLayout(self.dockWidgetContents_2)
        self.gridLayout_27.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_27.setSpacing(6)
        self.gridLayout_27.setObjectName("gridLayout_27")
        self.logsTextEdit = QtWidgets.QTextEdit(self.dockWidgetContents_2)
        self.logsTextEdit.setAcceptDrops(False)
        self.logsTextEdit.setAutoFillBackground(True)
        self.logsTextEdit.setStyleSheet("background: rgb(76, 76, 76)")
        self.logsTextEdit.setUndoRedoEnabled(False)
        self.logsTextEdit.setReadOnly(True)
        self.logsTextEdit.setAcceptRichText(True)
        self.logsTextEdit.setObjectName("logsTextEdit")
        self.gridLayout_27.addWidget(self.logsTextEdit, 0, 0, 1, 1)
        self.dockWidget.setWidget(self.dockWidgetContents_2)
        DialogGUI.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget)
        self.actionConnect = QtWidgets.QAction(DialogGUI)
        self.actionConnect.setCheckable(False)
        self.actionConnect.setChecked(False)
        self.actionConnect.setEnabled(True)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/hreresources/icons/connect.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionConnect.setIcon(icon1)
        self.actionConnect.setIconVisibleInMenu(True)
        self.actionConnect.setObjectName("actionConnect")
        self.actionDisconnect = QtWidgets.QAction(DialogGUI)
        self.actionDisconnect.setCheckable(False)
        self.actionDisconnect.setEnabled(False)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/hreresources/icons/disconnect1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDisconnect.setIcon(icon2)
        self.actionDisconnect.setObjectName("actionDisconnect")
        self.actionDatabaseConnect = QtWidgets.QAction(DialogGUI)
        self.actionDatabaseConnect.setCheckable(False)
        self.actionDatabaseConnect.setEnabled(False)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/hreresources/icons/database-connect.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDatabaseConnect.setIcon(icon3)
        self.actionDatabaseConnect.setObjectName("actionDatabaseConnect")
        self.actionWakeUp = QtWidgets.QAction(DialogGUI)
        self.actionWakeUp.setCheckable(False)
        self.actionWakeUp.setEnabled(False)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/hreresources/icons/eyeon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionWakeUp.setIcon(icon4)
        self.actionWakeUp.setObjectName("actionWakeUp")
        self.actionRest = QtWidgets.QAction(DialogGUI)
        self.actionRest.setCheckable(False)
        self.actionRest.setEnabled(False)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/hreresources/icons/eyeoff.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRest.setIcon(icon5)
        self.actionRest.setObjectName("actionRest")
        self.actionDatabaseDisconnect = QtWidgets.QAction(DialogGUI)
        self.actionDatabaseDisconnect.setCheckable(False)
        self.actionDatabaseDisconnect.setEnabled(False)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/hreresources/icons/database-disconnect.png"), QtGui.QIcon.Normal,
                        QtGui.QIcon.Off)
        self.actionDatabaseDisconnect.setIcon(icon6)
        self.actionDatabaseDisconnect.setObjectName("actionDatabaseDisconnect")
        self.actionStartCamera = QtWidgets.QAction(DialogGUI)
        self.actionStartCamera.setEnabled(False)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/hreresources/icons/camera-start1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionStartCamera.setIcon(icon7)
        self.actionStartCamera.setObjectName("actionStartCamera")
        self.actionStopCamera = QtWidgets.QAction(DialogGUI)
        self.actionStopCamera.setEnabled(False)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/hreresources/icons/camera-stop1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionStopCamera.setIcon(icon8)
        self.actionStopCamera.setObjectName("actionStopCamera")
        self.actionDelete = QtWidgets.QAction(DialogGUI)
        self.actionDelete.setEnabled(False)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/hreresources/icons/delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDelete.setIcon(icon9)
        self.actionDelete.setObjectName("actionDelete")
        self.actionEnableTouch = QtWidgets.QAction(DialogGUI)
        self.actionEnableTouch.setEnabled(False)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/hreresources/icons/touch.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionEnableTouch.setIcon(icon10)
        self.actionEnableTouch.setObjectName("actionEnableTouch")
        self.actionReload = QtWidgets.QAction(DialogGUI)
        self.actionReload.setCheckable(False)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/hreresources/icons/refresh.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionReload.setIcon(icon11)
        self.actionReload.setObjectName("actionReload")
        self.actionSave = QtWidgets.QAction(DialogGUI)
        self.actionSave.setEnabled(False)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/hreresources/icons/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave.setIcon(icon12)
        self.actionSave.setObjectName("actionSave")
        self.actionTabletShow = QtWidgets.QAction(DialogGUI)
        self.actionTabletShow.setEnabled(False)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/hreresources/icons/tablet-show.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionTabletShow.setIcon(icon13)
        self.actionTabletShow.setObjectName("actionTabletShow")
        self.actionTabletHide = QtWidgets.QAction(DialogGUI)
        self.actionTabletHide.setEnabled(False)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/hreresources/icons/tablet-hide.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionTabletHide.setIcon(icon14)
        self.actionTabletHide.setObjectName("actionTabletHide")
        self.actionVolumeDown = QtWidgets.QAction(DialogGUI)
        self.actionVolumeDown.setEnabled(False)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/hreresources/icons/volume-down.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionVolumeDown.setIcon(icon15)
        self.actionVolumeDown.setObjectName("actionVolumeDown")
        self.actionVolumeUp = QtWidgets.QAction(DialogGUI)
        self.actionVolumeUp.setEnabled(False)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/hreresources/icons/volume-up.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionVolumeUp.setIcon(icon16)
        self.actionVolumeUp.setObjectName("actionVolumeUp")
        self.actionPlay = QtWidgets.QAction(DialogGUI)
        self.actionPlay.setCheckable(False)
        self.actionPlay.setEnabled(False)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(":/hreresources/icons/play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPlay.setIcon(icon17)
        self.actionPlay.setObjectName("actionPlay")
        self.actionEnableTracking = QtWidgets.QAction(DialogGUI)
        self.actionEnableTracking.setEnabled(False)
        self.actionEnableTracking.setIcon(icon4)
        self.actionEnableTracking.setObjectName("actionEnableTracking")
        self.actionDisableTracking = QtWidgets.QAction(DialogGUI)
        self.actionDisableTracking.setEnabled(False)
        self.actionDisableTracking.setIcon(icon5)
        self.actionDisableTracking.setObjectName("actionDisableTracking")
        self.actionStop = QtWidgets.QAction(DialogGUI)
        self.actionStop.setEnabled(False)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(":/hreresources/icons/stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionStop.setIcon(icon18)
        self.actionStop.setObjectName("actionStop")
        self.actionImportBlocks = QtWidgets.QAction(DialogGUI)
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(":/hreresources/icons/import.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionImportBlocks.setIcon(icon19)
        self.actionImportBlocks.setObjectName("actionImportBlocks")
        self.actionExportBlocks = QtWidgets.QAction(DialogGUI)
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap(":/hreresources/icons/export.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExportBlocks.setIcon(icon20)
        self.actionExportBlocks.setObjectName("actionExportBlocks")
        self.actionCopySettings = QtWidgets.QAction(DialogGUI)
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap(":/hreresources/icons/copy.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCopySettings.setIcon(icon21)
        self.actionCopySettings.setObjectName("actionCopySettings")
        self.actionPasteSettings = QtWidgets.QAction(DialogGUI)
        self.actionPasteSettings.setEnabled(False)
        icon22 = QtGui.QIcon()
        icon22.addPixmap(QtGui.QPixmap(":/hreresources/icons/paste.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPasteSettings.setIcon(icon22)
        self.actionPasteSettings.setObjectName("actionPasteSettings")
        self.mainToolBar.addAction(self.actionConnect)
        self.mainToolBar.addAction(self.actionDisconnect)
        self.mainToolBar.addSeparator()
        self.mainToolBar.addAction(self.actionDatabaseConnect)
        self.mainToolBar.addAction(self.actionDatabaseDisconnect)
        self.mainToolBar.addSeparator()
        self.mainToolBar.addAction(self.actionWakeUp)
        self.mainToolBar.addAction(self.actionRest)
        self.mainToolBar.addSeparator()
        self.mainToolBar.addAction(self.actionEnableTouch)
        self.mainToolBar.addSeparator()
        self.mainToolBar.addAction(self.actionTabletShow)
        self.mainToolBar.addAction(self.actionTabletHide)
        self.mainToolBar.addSeparator()
        self.mainToolBar.addAction(self.actionVolumeDown)
        self.mainToolBar.addAction(self.actionVolumeUp)
        self.mainToolBar.addSeparator()
        self.mainToolBar.addAction(self.actionPlay)
        self.mainToolBar.addAction(self.actionStop)
        self.mainToolBar.addSeparator()
        self.mainToolBar.addAction(self.actionImportBlocks)
        self.mainToolBar.addAction(self.actionExportBlocks)
        self.mainToolBar.addSeparator()
        self.mainToolBar.addAction(self.actionCopySettings)
        self.mainToolBar.addAction(self.actionPasteSettings)

        self.retranslateUi(DialogGUI)
        QtCore.QMetaObject.connectSlotsByName(DialogGUI)

    def retranslateUi(self, DialogGUI):
        _translate = QtCore.QCoreApplication.translate
        DialogGUI.setWindowTitle(_translate("DialogGUI", "Pepper Dialog"))
        self.label_8.setText(_translate("DialogGUI", "DESIGN PANEL"))
        self.clearDropListButton.setText(_translate("DialogGUI", "Clear"))
        self.deleteDropListItemsButton.setText(_translate("DialogGUI", "Delete"))
        self.saveDropListButton.setText(_translate("DialogGUI", "Save"))
        self.newBlockPushButton.setText(_translate("DialogGUI", "New Block"))
        self.enableMovingCheckBox.setText(_translate("DialogGUI", "Enable Moving"))
        self.label.setText(_translate("DialogGUI", "# Repetitions"))
        self.behavioralParametersDockWidget.setWindowTitle(_translate("DialogGUI", "Behavioral Parameters"))
        self.groupBox_6.setTitle(_translate("DialogGUI", "Voice"))
        self.label_19.setText(_translate("DialogGUI", "Fast"))
        self.label_18.setText(_translate("DialogGUI", "Slow"))
        self.label_6.setText(_translate("DialogGUI", "High"))
        self.label_14.setText(_translate("DialogGUI", "Low"))
        self.voiceSpeedLabel.setText(_translate("DialogGUI", "Speed"))
        self.voicePitchLabel.setText(_translate("DialogGUI", "Pitch"))
        self.label_15.setText(_translate("DialogGUI", "Prosody"))
        self.label_16.setText(_translate("DialogGUI", "Weak"))
        self.label_17.setText(_translate("DialogGUI", "Strong"))
        self.behavioralParametersApplyToAllButton.setText(_translate("DialogGUI", "Apply to All"))
        self.behavioralParametersApplyComboBox.setItemText(0, _translate("DialogGUI", "All Parameters"))
        self.behavioralParametersApplyComboBox.setItemText(1, _translate("DialogGUI", "Gesture Openness"))
        self.behavioralParametersApplyComboBox.setItemText(2, _translate("DialogGUI", "Gaze Pattern"))
        self.behavioralParametersApplyComboBox.setItemText(3, _translate("DialogGUI", "Proxemic Closeness"))
        self.behavioralParametersApplyComboBox.setItemText(4, _translate("DialogGUI", "Voice"))
        self.behavioralParametersApplyComboBox.setItemText(5, _translate("DialogGUI", "Eye Color"))
        self.behavioralParametersApplyToItemsBelowButton.setText(_translate("DialogGUI", "Apply ⇣"))
        self.groupBox.setTitle(_translate("DialogGUI", "Eye Color"))
        self.greenEyeColorRadioButton.setText(_translate("DialogGUI", "Green"))
        self.blueEyeColorRadioButton.setText(_translate("DialogGUI", "Blue"))
        self.redEyeColorRadioButton.setText(_translate("DialogGUI", "Red"))
        self.whiteEyeColorRadioButton.setText(_translate("DialogGUI", "White"))
        self.groupBox_4.setTitle(_translate("DialogGUI", "Gaze Pattern"))
        self.label_12.setText(_translate("DialogGUI", "Fixated"))
        self.label_13.setText(_translate("DialogGUI", "Diverted"))
        self.groupBox_7.setTitle(_translate("DialogGUI", "Proxemic Closeness"))
        self.label_4.setText(_translate("DialogGUI", "Far"))
        self.label_3.setText(_translate("DialogGUI", "Close"))
        self.testBehavioralParametersButton.setText(_translate("DialogGUI", "Test"))
        self.behavioralParametersApplyButton.setText(_translate("DialogGUI", "Apply"))
        self.warningLabel.setText(_translate("DialogGUI", "Click \'Apply\' to save the changes."))
        self.groupBox_5.setTitle(_translate("DialogGUI", "Gesture Openness"))
        self.label_2.setText(_translate("DialogGUI", "Open"))
        self.label_10.setText(_translate("DialogGUI", "Close"))
        self.blocksDockWidget.setWindowTitle(_translate("DialogGUI", "Dialogue Blocks"))
        self.dragListWidget.setSortingEnabled(True)
        __sortingEnabled = self.dragListWidget.isSortingEnabled()
        self.dragListWidget.setSortingEnabled(False)
        item = self.dragListWidget.item(0)
        item.setText(_translate("DialogGUI", "Salutation"))
        self.dragListWidget.setSortingEnabled(__sortingEnabled)
        self.dialogueBlocksCategoryComboBox.setItemText(0, _translate("DialogGUI", "All"))
        self.dialogueBlocksCategoryComboBox.setItemText(1, _translate("DialogGUI", "Opening"))
        self.dialogueBlocksCategoryComboBox.setItemText(2, _translate("DialogGUI", "Service-Provision"))
        self.dialogueBlocksCategoryComboBox.setItemText(3, _translate("DialogGUI", "Closing"))
        self.dialogueBlocksCategoryComboBox.setItemText(4, _translate("DialogGUI", "Chit-Chat"))
        self.dockWidget.setWindowTitle(_translate("DialogGUI", "Logs"))
        self.actionConnect.setText(_translate("DialogGUI", "Connect"))
        self.actionDisconnect.setText(_translate("DialogGUI", "Disconnect"))
        self.actionDatabaseConnect.setText(_translate("DialogGUI", "DB Connect"))
        self.actionWakeUp.setText(_translate("DialogGUI", "WakeUp"))
        self.actionRest.setText(_translate("DialogGUI", "Rest"))
        self.actionDatabaseDisconnect.setText(_translate("DialogGUI", "DB Disconnect"))
        self.actionStartCamera.setText(_translate("DialogGUI", "Start"))
        self.actionStopCamera.setText(_translate("DialogGUI", "Stop"))
        self.actionDelete.setText(_translate("DialogGUI", "Delete"))
        self.actionDelete.setToolTip(_translate("DialogGUI", "Delete"))
        self.actionEnableTouch.setText(_translate("DialogGUI", "Enable Touch"))
        self.actionReload.setText(_translate("DialogGUI", "Reload"))
        self.actionReload.setToolTip(_translate("DialogGUI", "Reload"))
        self.actionSave.setText(_translate("DialogGUI", "Save Blocks"))
        self.actionTabletShow.setText(_translate("DialogGUI", "Show"))
        self.actionTabletHide.setText(_translate("DialogGUI", "Hide"))
        self.actionVolumeDown.setText(_translate("DialogGUI", "Vol-"))
        self.actionVolumeUp.setText(_translate("DialogGUI", "Vol+"))
        self.actionPlay.setText(_translate("DialogGUI", "Play"))
        self.actionPlay.setToolTip(_translate("DialogGUI", "Play"))
        self.actionEnableTracking.setText(_translate("DialogGUI", "Enable Tracking"))
        self.actionDisableTracking.setText(_translate("DialogGUI", "Disable Tracking"))
        self.actionStop.setText(_translate("DialogGUI", "Stop"))
        self.actionImportBlocks.setText(_translate("DialogGUI", "Import Blocks"))
        self.actionExportBlocks.setText(_translate("DialogGUI", "Export Blocks"))
        self.actionCopySettings.setText(_translate("DialogGUI", "Copy Settings"))
        self.actionPasteSettings.setText(_translate("DialogGUI", "Paste Settings"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    DialogGUI = QtWidgets.QMainWindow()
    ui = Ui_DialogGUI()
    ui.setupUi(DialogGUI)
    DialogGUI.show()
    sys.exit(app.exec_())
