# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'dialogmainwindow.ui'
##
## Created by: Qt User Interface Compiler version 5.15.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *

import interaction_manager.view.resources_rc

class Ui_DialogGUI(object):
    def setupUi(self, DialogGUI):
        if not DialogGUI.objectName():
            DialogGUI.setObjectName(u"DialogGUI")
        DialogGUI.resize(1216, 769)
        DialogGUI.setMinimumSize(QSize(62, 50))
        DialogGUI.setAutoFillBackground(True)
        self.actionReload = QAction(DialogGUI)
        self.actionReload.setObjectName(u"actionReload")
        self.actionReload.setCheckable(False)
        icon = QIcon()
        icon.addFile(u":/hreresources/icons/refresh.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionReload.setIcon(icon)
        self.actionMenuNew = QAction(DialogGUI)
        self.actionMenuNew.setObjectName(u"actionMenuNew")
        self.actionMenuImportBlocks = QAction(DialogGUI)
        self.actionMenuImportBlocks.setObjectName(u"actionMenuImportBlocks")
        self.actionMenuImportBlocks.setEnabled(True)
        icon1 = QIcon()
        icon1.addFile(u":/hreresources/icons/import.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionMenuImportBlocks.setIcon(icon1)
        self.actionMenuExportBlocks = QAction(DialogGUI)
        self.actionMenuExportBlocks.setObjectName(u"actionMenuExportBlocks")
        self.actionMenuExportBlocks.setEnabled(True)
        icon2 = QIcon()
        icon2.addFile(u":/hreresources/icons/export.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionMenuExportBlocks.setIcon(icon2)
        self.actionMenuSave = QAction(DialogGUI)
        self.actionMenuSave.setObjectName(u"actionMenuSave")
        icon3 = QIcon()
        icon3.addFile(u":/hreresources/icons/save.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionMenuSave.setIcon(icon3)
        self.actionMenuSaveAs = QAction(DialogGUI)
        self.actionMenuSaveAs.setObjectName(u"actionMenuSaveAs")
        self.actionMenuSaveAs.setIcon(icon3)
        self.actionMenuExit = QAction(DialogGUI)
        self.actionMenuExit.setObjectName(u"actionMenuExit")
        self.actionMenuUndo = QAction(DialogGUI)
        self.actionMenuUndo.setObjectName(u"actionMenuUndo")
        self.actionMenuUndo.setEnabled(True)
        self.actionMenuRedo = QAction(DialogGUI)
        self.actionMenuRedo.setObjectName(u"actionMenuRedo")
        self.actionMenuRedo.setEnabled(True)
        self.actionMenuCopy = QAction(DialogGUI)
        self.actionMenuCopy.setObjectName(u"actionMenuCopy")
        self.actionMenuCopy.setEnabled(False)
        icon4 = QIcon()
        icon4.addFile(u":/hreresources/icons/copy.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionMenuCopy.setIcon(icon4)
        self.actionMenuPaste = QAction(DialogGUI)
        self.actionMenuPaste.setObjectName(u"actionMenuPaste")
        self.actionMenuPaste.setEnabled(False)
        icon5 = QIcon()
        icon5.addFile(u":/hreresources/icons/paste.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionMenuPaste.setIcon(icon5)
        self.actionMenuPasteParameters = QAction(DialogGUI)
        self.actionMenuPasteParameters.setObjectName(u"actionMenuPasteParameters")
        self.actionMenuPasteParameters.setEnabled(False)
        self.actionMenuPasteParameters.setIcon(icon5)
        self.actionMenuDelete = QAction(DialogGUI)
        self.actionMenuDelete.setObjectName(u"actionMenuDelete")
        self.actionMenuDelete.setEnabled(True)
        icon6 = QIcon()
        icon6.addFile(u":/hreresources/icons/delete.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionMenuDelete.setIcon(icon6)
        self.actionMenuClear = QAction(DialogGUI)
        self.actionMenuClear.setObjectName(u"actionMenuClear")
        icon7 = QIcon()
        icon7.addFile(u":/hreresources/icons/erase.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionMenuClear.setIcon(icon7)
        self.actionMenuConnect = QAction(DialogGUI)
        self.actionMenuConnect.setObjectName(u"actionMenuConnect")
        self.actionMenuConnect.setEnabled(True)
        icon8 = QIcon()
        icon8.addFile(u":/hreresources/icons/connect.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionMenuConnect.setIcon(icon8)
        self.actionMenuDisconnect = QAction(DialogGUI)
        self.actionMenuDisconnect.setObjectName(u"actionMenuDisconnect")
        self.actionMenuDisconnect.setEnabled(False)
        icon9 = QIcon()
        icon9.addFile(u":/hreresources/icons/disconnect1.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionMenuDisconnect.setIcon(icon9)
        self.actionMenuWakeUp = QAction(DialogGUI)
        self.actionMenuWakeUp.setObjectName(u"actionMenuWakeUp")
        self.actionMenuWakeUp.setEnabled(False)
        icon10 = QIcon()
        icon10.addFile(u":/hreresources/icons/eyeon.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionMenuWakeUp.setIcon(icon10)
        self.actionMenuRest = QAction(DialogGUI)
        self.actionMenuRest.setObjectName(u"actionMenuRest")
        self.actionMenuRest.setEnabled(False)
        icon11 = QIcon()
        icon11.addFile(u":/hreresources/icons/eyeoff.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionMenuRest.setIcon(icon11)
        self.actionMenuEnableTouch = QAction(DialogGUI)
        self.actionMenuEnableTouch.setObjectName(u"actionMenuEnableTouch")
        self.actionMenuEnableTouch.setEnabled(False)
        icon12 = QIcon()
        icon12.addFile(u":/hreresources/icons/touch.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionMenuEnableTouch.setIcon(icon12)
        self.actionMenuShowImage = QAction(DialogGUI)
        self.actionMenuShowImage.setObjectName(u"actionMenuShowImage")
        self.actionMenuShowImage.setEnabled(False)
        icon13 = QIcon()
        icon13.addFile(u":/hreresources/icons/tablet-show.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionMenuShowImage.setIcon(icon13)
        self.actionMenuHideImage = QAction(DialogGUI)
        self.actionMenuHideImage.setObjectName(u"actionMenuHideImage")
        self.actionMenuHideImage.setEnabled(False)
        icon14 = QIcon()
        icon14.addFile(u":/hreresources/icons/tablet-hide.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionMenuHideImage.setIcon(icon14)
        self.actionMenuVolumeUp = QAction(DialogGUI)
        self.actionMenuVolumeUp.setObjectName(u"actionMenuVolumeUp")
        self.actionMenuVolumeUp.setEnabled(False)
        icon15 = QIcon()
        icon15.addFile(u":/hreresources/icons/volume-up.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionMenuVolumeUp.setIcon(icon15)
        self.actionMenuVolumeDown = QAction(DialogGUI)
        self.actionMenuVolumeDown.setObjectName(u"actionMenuVolumeDown")
        self.actionMenuVolumeDown.setEnabled(False)
        icon16 = QIcon()
        icon16.addFile(u":/hreresources/icons/volume-down.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionMenuVolumeDown.setIcon(icon16)
        self.actionMenuTest = QAction(DialogGUI)
        self.actionMenuTest.setObjectName(u"actionMenuTest")
        self.actionMenuTest.setEnabled(False)
        self.actionMenuPlay = QAction(DialogGUI)
        self.actionMenuPlay.setObjectName(u"actionMenuPlay")
        self.actionMenuPlay.setEnabled(False)
        icon17 = QIcon()
        icon17.addFile(u":/hreresources/icons/play.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionMenuPlay.setIcon(icon17)
        self.actionMenuPause = QAction(DialogGUI)
        self.actionMenuPause.setObjectName(u"actionMenuPause")
        self.actionMenuPause.setEnabled(False)
        icon18 = QIcon()
        icon18.addFile(u":/hreresources/icons/pause.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionMenuPause.setIcon(icon18)
        self.actionMenuStop = QAction(DialogGUI)
        self.actionMenuStop.setObjectName(u"actionMenuStop")
        self.actionMenuStop.setEnabled(False)
        icon19 = QIcon()
        icon19.addFile(u":/hreresources/icons/stop.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionMenuStop.setIcon(icon19)
        self.actionMenuEnableMoving = QAction(DialogGUI)
        self.actionMenuEnableMoving.setObjectName(u"actionMenuEnableMoving")
        self.actionMenuEnableMoving.setEnabled(False)
        self.actionMenuDisableMoving = QAction(DialogGUI)
        self.actionMenuDisableMoving.setObjectName(u"actionMenuDisableMoving")
        self.actionMenuDisableMoving.setEnabled(False)
        self.actionMenuDatabaseConnect = QAction(DialogGUI)
        self.actionMenuDatabaseConnect.setObjectName(u"actionMenuDatabaseConnect")
        icon20 = QIcon()
        icon20.addFile(u":/hreresources/icons/database-connect.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionMenuDatabaseConnect.setIcon(icon20)
        self.actionMenuDatabaseDisconnect = QAction(DialogGUI)
        self.actionMenuDatabaseDisconnect.setObjectName(u"actionMenuDatabaseDisconnect")
        self.actionMenuDatabaseDisconnect.setEnabled(False)
        icon21 = QIcon()
        icon21.addFile(u":/hreresources/icons/database-disconnect.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionMenuDatabaseDisconnect.setIcon(icon21)
        self.actionMenuZoomIn = QAction(DialogGUI)
        self.actionMenuZoomIn.setObjectName(u"actionMenuZoomIn")
        icon22 = QIcon()
        icon22.addFile(u":/hreresources/icons/zoomin.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionMenuZoomIn.setIcon(icon22)
        self.actionMenuZoomOut = QAction(DialogGUI)
        self.actionMenuZoomOut.setObjectName(u"actionMenuZoomOut")
        icon23 = QIcon()
        icon23.addFile(u":/hreresources/icons/zoomout.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionMenuZoomOut.setIcon(icon23)
        self.actionMenuBlockList = QAction(DialogGUI)
        self.actionMenuBlockList.setObjectName(u"actionMenuBlockList")
        self.actionMenuLogs = QAction(DialogGUI)
        self.actionMenuLogs.setObjectName(u"actionMenuLogs")
        self.actionMenuSimulate = QAction(DialogGUI)
        self.actionMenuSimulate.setObjectName(u"actionMenuSimulate")
        icon24 = QIcon()
        icon24.addFile(u":/hreresources/icons/simulate-chat.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionMenuSimulate.setIcon(icon24)
        self.actionMenuMusic = QAction(DialogGUI)
        self.actionMenuMusic.setObjectName(u"actionMenuMusic")
        icon25 = QIcon()
        icon25.addFile(u":/hreresources/icons/music.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionMenuMusic.setIcon(icon25)
        self.actionMenuMusicDockView = QAction(DialogGUI)
        self.actionMenuMusicDockView.setObjectName(u"actionMenuMusicDockView")
        self.actionMenuSimulationDockView = QAction(DialogGUI)
        self.actionMenuSimulationDockView.setObjectName(u"actionMenuSimulationDockView")
        self.actionMenuSettingsDockView = QAction(DialogGUI)
        self.actionMenuSettingsDockView.setObjectName(u"actionMenuSettingsDockView")
        self.centralWidget = QWidget(DialogGUI)
        self.centralWidget.setObjectName(u"centralWidget")
        self.gridLayout_11 = QGridLayout(self.centralWidget)
        self.gridLayout_11.setSpacing(6)
        self.gridLayout_11.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_11.setObjectName(u"gridLayout_11")
        self.label_8 = QLabel(self.centralWidget)
        self.label_8.setObjectName(u"label_8")
        sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        font = QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setAlignment(Qt.AlignCenter)

        self.gridLayout_11.addWidget(self.label_8, 0, 0, 1, 1)

        self.line = QFrame(self.centralWidget)
        self.line.setObjectName(u"line")
        self.line.setFrameShape(QFrame.HLine)
        self.line.setFrameShadow(QFrame.Sunken)

        self.gridLayout_11.addWidget(self.line, 1, 0, 1, 1)

        self.gridLayout_2 = QGridLayout()
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.designPanelLayout = QGridLayout()
        self.designPanelLayout.setSpacing(6)
        self.designPanelLayout.setObjectName(u"designPanelLayout")
        self.tmpWidget = QWidget(self.centralWidget)
        self.tmpWidget.setObjectName(u"tmpWidget")
        sizePolicy1 = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.MinimumExpanding)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.tmpWidget.sizePolicy().hasHeightForWidth())
        self.tmpWidget.setSizePolicy(sizePolicy1)

        self.designPanelLayout.addWidget(self.tmpWidget, 0, 0, 1, 1)


        self.gridLayout_2.addLayout(self.designPanelLayout, 0, 0, 1, 1)


        self.gridLayout_11.addLayout(self.gridLayout_2, 2, 0, 1, 1)

        DialogGUI.setCentralWidget(self.centralWidget)
        self.menuBar = QMenuBar(DialogGUI)
        self.menuBar.setObjectName(u"menuBar")
        self.menuBar.setGeometry(QRect(0, 0, 1216, 22))
        self.menuFile = QMenu(self.menuBar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuEdit = QMenu(self.menuBar)
        self.menuEdit.setObjectName(u"menuEdit")
        self.menuRobot = QMenu(self.menuBar)
        self.menuRobot.setObjectName(u"menuRobot")
        self.menuDatabase = QMenu(self.menuBar)
        self.menuDatabase.setObjectName(u"menuDatabase")
        self.menuView = QMenu(self.menuBar)
        self.menuView.setObjectName(u"menuView")
        DialogGUI.setMenuBar(self.menuBar)
        self.mainToolBar = QToolBar(DialogGUI)
        self.mainToolBar.setObjectName(u"mainToolBar")
        self.mainToolBar.setEnabled(True)
        self.mainToolBar.setAllowedAreas(Qt.AllToolBarAreas)
        self.mainToolBar.setOrientation(Qt.Horizontal)
        self.mainToolBar.setToolButtonStyle(Qt.ToolButtonTextUnderIcon)
        DialogGUI.addToolBar(Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QStatusBar(DialogGUI)
        self.statusBar.setObjectName(u"statusBar")
        DialogGUI.setStatusBar(self.statusBar)
        self.blocksDockWidget = QDockWidget(DialogGUI)
        self.blocksDockWidget.setObjectName(u"blocksDockWidget")
        self.blocksDockWidget.setFont(font)
        self.blocksDockWidget.setFeatures(QDockWidget.DockWidgetFloatable|QDockWidget.DockWidgetMovable)
        self.dockWidgetContents = QWidget()
        self.dockWidgetContents.setObjectName(u"dockWidgetContents")
        self.gridLayout_8 = QGridLayout(self.dockWidgetContents)
        self.gridLayout_8.setSpacing(6)
        self.gridLayout_8.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_8.setObjectName(u"gridLayout_8")
        self.gridLayout_3 = QGridLayout()
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName(u"gridLayout_3")
        self.groupBox_11 = QGroupBox(self.dockWidgetContents)
        self.groupBox_11.setObjectName(u"groupBox_11")
        font1 = QFont()
        font1.setBold(False)
        font1.setWeight(50)
        self.groupBox_11.setFont(font1)
        self.gridLayout_7 = QGridLayout(self.groupBox_11)
        self.gridLayout_7.setSpacing(6)
        self.gridLayout_7.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_7.setObjectName(u"gridLayout_7")
        self.dialogueBlocksCategoryComboBox = QComboBox(self.groupBox_11)
        self.dialogueBlocksCategoryComboBox.addItem("")
        self.dialogueBlocksCategoryComboBox.addItem("")
        self.dialogueBlocksCategoryComboBox.addItem("")
        self.dialogueBlocksCategoryComboBox.addItem("")
        self.dialogueBlocksCategoryComboBox.addItem("")
        self.dialogueBlocksCategoryComboBox.setObjectName(u"dialogueBlocksCategoryComboBox")

        self.gridLayout_7.addWidget(self.dialogueBlocksCategoryComboBox, 0, 0, 1, 1)

        self.line_3 = QFrame(self.groupBox_11)
        self.line_3.setObjectName(u"line_3")
        self.line_3.setFrameShape(QFrame.HLine)
        self.line_3.setFrameShadow(QFrame.Sunken)

        self.gridLayout_7.addWidget(self.line_3, 1, 0, 1, 1)

        self.dragListWidget = QListWidget(self.groupBox_11)
        icon26 = QIcon()
        icon26.addFile(u":/hreresources/pepper-icons/pepper-greet.png", QSize(), QIcon.Normal, QIcon.Off)
        font2 = QFont()
        font2.setPointSize(13)
        font2.setBold(False)
        font2.setWeight(50)
        __qlistwidgetitem = QListWidgetItem(self.dragListWidget)
        __qlistwidgetitem.setFont(font2);
        __qlistwidgetitem.setIcon(icon26);
        self.dragListWidget.setObjectName(u"dragListWidget")
        self.dragListWidget.setFont(font2)
        self.dragListWidget.setLineWidth(1)
        self.dragListWidget.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOn)
        self.dragListWidget.setDragEnabled(True)
        self.dragListWidget.setDragDropMode(QAbstractItemView.DragOnly)
        self.dragListWidget.setAlternatingRowColors(True)
        self.dragListWidget.setIconSize(QSize(100, 60))
        self.dragListWidget.setWordWrap(True)
        self.dragListWidget.setSelectionRectVisible(True)
        self.dragListWidget.setSortingEnabled(True)

        self.gridLayout_7.addWidget(self.dragListWidget, 2, 0, 1, 1)


        self.gridLayout_3.addWidget(self.groupBox_11, 0, 0, 1, 2)


        self.gridLayout_8.addLayout(self.gridLayout_3, 0, 0, 1, 1)

        self.blocksDockWidget.setWidget(self.dockWidgetContents)
        DialogGUI.addDockWidget(Qt.LeftDockWidgetArea, self.blocksDockWidget)
        self.logsDockWidget = QDockWidget(DialogGUI)
        self.logsDockWidget.setObjectName(u"logsDockWidget")
        sizePolicy.setHeightForWidth(self.logsDockWidget.sizePolicy().hasHeightForWidth())
        self.logsDockWidget.setSizePolicy(sizePolicy)
        self.logsDockWidget.setMinimumSize(QSize(182, 177))
        self.logsDockWidget.setFloating(False)
        self.logsDockWidget.setFeatures(QDockWidget.AllDockWidgetFeatures)
        self.logsDockWidget.setAllowedAreas(Qt.AllDockWidgetAreas)
        self.dockWidgetContents_2 = QWidget()
        self.dockWidgetContents_2.setObjectName(u"dockWidgetContents_2")
        self.gridLayout_27 = QGridLayout(self.dockWidgetContents_2)
        self.gridLayout_27.setSpacing(6)
        self.gridLayout_27.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_27.setObjectName(u"gridLayout_27")
        self.logsTextEdit = QTextEdit(self.dockWidgetContents_2)
        self.logsTextEdit.setObjectName(u"logsTextEdit")
        self.logsTextEdit.setAcceptDrops(False)
        self.logsTextEdit.setAutoFillBackground(True)
        self.logsTextEdit.setStyleSheet(u"background: rgb(76, 76, 76)")
        self.logsTextEdit.setUndoRedoEnabled(False)
        self.logsTextEdit.setReadOnly(True)
        self.logsTextEdit.setAcceptRichText(True)

        self.gridLayout_27.addWidget(self.logsTextEdit, 0, 0, 1, 1)

        self.logsDockWidget.setWidget(self.dockWidgetContents_2)
        DialogGUI.addDockWidget(Qt.LeftDockWidgetArea, self.logsDockWidget)
        self.musicDockWidget = QDockWidget(DialogGUI)
        self.musicDockWidget.setObjectName(u"musicDockWidget")
        sizePolicy.setHeightForWidth(self.musicDockWidget.sizePolicy().hasHeightForWidth())
        self.musicDockWidget.setSizePolicy(sizePolicy)
        self.dockWidgetContents_3 = QWidget()
        self.dockWidgetContents_3.setObjectName(u"dockWidgetContents_3")
        self.gridLayout_16 = QGridLayout(self.dockWidgetContents_3)
        self.gridLayout_16.setSpacing(6)
        self.gridLayout_16.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_16.setObjectName(u"gridLayout_16")
        self.verticalSpacer_4 = QSpacerItem(20, 40, QSizePolicy.Minimum, QSizePolicy.Expanding)

        self.gridLayout_16.addItem(self.verticalSpacer_4, 2, 0, 1, 1)

        self.gridLayout_10 = QGridLayout()
        self.gridLayout_10.setSpacing(6)
        self.gridLayout_10.setObjectName(u"gridLayout_10")
        self.musicPlaylistComboBox = QComboBox(self.dockWidgetContents_3)
        self.musicPlaylistComboBox.setObjectName(u"musicPlaylistComboBox")

        self.gridLayout_10.addWidget(self.musicPlaylistComboBox, 0, 1, 1, 1)

        self.musicTracksComboBox = QComboBox(self.dockWidgetContents_3)
        self.musicTracksComboBox.setObjectName(u"musicTracksComboBox")

        self.gridLayout_10.addWidget(self.musicTracksComboBox, 1, 1, 1, 1)

        self.label = QLabel(self.dockWidgetContents_3)
        self.label.setObjectName(u"label")
        sizePolicy2 = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Preferred)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy2)

        self.gridLayout_10.addWidget(self.label, 0, 0, 1, 1)

        self.label_5 = QLabel(self.dockWidgetContents_3)
        self.label_5.setObjectName(u"label_5")
        sizePolicy2.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy2)

        self.gridLayout_10.addWidget(self.label_5, 1, 0, 1, 1)


        self.gridLayout_16.addLayout(self.gridLayout_10, 0, 0, 1, 1)

        self.gridLayout_9 = QGridLayout()
        self.gridLayout_9.setSpacing(6)
        self.gridLayout_9.setObjectName(u"gridLayout_9")
        self.musicPauseButton = QPushButton(self.dockWidgetContents_3)
        self.musicPauseButton.setObjectName(u"musicPauseButton")
        self.musicPauseButton.setEnabled(False)
        icon27 = QIcon()
        icon27.addFile(u":/hreresources/icons/pause.png", QSize(), QIcon.Normal, QIcon.On)
        self.musicPauseButton.setIcon(icon27)

        self.gridLayout_9.addWidget(self.musicPauseButton, 0, 1, 1, 1)

        self.musicPlayButton = QPushButton(self.dockWidgetContents_3)
        self.musicPlayButton.setObjectName(u"musicPlayButton")
        self.musicPlayButton.setEnabled(False)
        icon28 = QIcon()
        icon28.addFile(u":/hreresources/icons/play.png", QSize(), QIcon.Normal, QIcon.On)
        self.musicPlayButton.setIcon(icon28)

        self.gridLayout_9.addWidget(self.musicPlayButton, 0, 2, 1, 1)

        self.musicMessageLineEdit = QLineEdit(self.dockWidgetContents_3)
        self.musicMessageLineEdit.setObjectName(u"musicMessageLineEdit")
        self.musicMessageLineEdit.setLayoutDirection(Qt.LeftToRight)
        self.musicMessageLineEdit.setAutoFillBackground(False)
        self.musicMessageLineEdit.setStyleSheet(u"background-color: transparent;")
        self.musicMessageLineEdit.setFrame(False)
        self.musicMessageLineEdit.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.musicMessageLineEdit.setReadOnly(True)

        self.gridLayout_9.addWidget(self.musicMessageLineEdit, 2, 0, 1, 4)

        self.musicVolumeSpinBox = QSpinBox(self.dockWidgetContents_3)
        self.musicVolumeSpinBox.setObjectName(u"musicVolumeSpinBox")
        self.musicVolumeSpinBox.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.musicVolumeSpinBox.setMaximum(100)
        self.musicVolumeSpinBox.setSingleStep(5)
        self.musicVolumeSpinBox.setValue(70)

        self.gridLayout_9.addWidget(self.musicVolumeSpinBox, 1, 2, 1, 1)

        self.musicVolumeButton = QPushButton(self.dockWidgetContents_3)
        self.musicVolumeButton.setObjectName(u"musicVolumeButton")
        self.musicVolumeButton.setEnabled(False)

        self.gridLayout_9.addWidget(self.musicVolumeButton, 1, 1, 1, 1)

        self.horizontalSpacer = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.gridLayout_9.addItem(self.horizontalSpacer, 0, 0, 1, 1)


        self.gridLayout_16.addLayout(self.gridLayout_9, 1, 0, 1, 1)

        self.musicDockWidget.setWidget(self.dockWidgetContents_3)
        DialogGUI.addDockWidget(Qt.LeftDockWidgetArea, self.musicDockWidget)
        self.settingsDockWidget = QDockWidget(DialogGUI)
        self.settingsDockWidget.setObjectName(u"settingsDockWidget")
        self.dockWidgetContents_6 = QWidget()
        self.dockWidgetContents_6.setObjectName(u"dockWidgetContents_6")
        self.gridLayout_4 = QGridLayout(self.dockWidgetContents_6)
        self.gridLayout_4.setSpacing(6)
        self.gridLayout_4.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_4.setObjectName(u"gridLayout_4")
        self.gridLayout = QGridLayout()
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName(u"gridLayout")
        self.blocksDelaySpinBox = QSpinBox(self.dockWidgetContents_6)
        self.blocksDelaySpinBox.setObjectName(u"blocksDelaySpinBox")
        self.blocksDelaySpinBox.setEnabled(False)
        self.blocksDelaySpinBox.setAlignment(Qt.AlignCenter)
        self.blocksDelaySpinBox.setMaximum(60)
        self.blocksDelaySpinBox.setValue(1)

        self.gridLayout.addWidget(self.blocksDelaySpinBox, 2, 1, 1, 1)

        self.groupBox = QGroupBox(self.dockWidgetContents_6)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setFont(font)
        self.gridLayout_6 = QGridLayout(self.groupBox)
        self.gridLayout_6.setSpacing(6)
        self.gridLayout_6.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_6.setObjectName(u"gridLayout_6")
        self.gridLayout_5 = QGridLayout()
        self.gridLayout_5.setSpacing(6)
        self.gridLayout_5.setObjectName(u"gridLayout_5")
        self.label_2 = QLabel(self.groupBox)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setFont(font1)

        self.gridLayout_5.addWidget(self.label_2, 0, 0, 1, 1)

        self.speechCertaintySpinBox = QSpinBox(self.groupBox)
        self.speechCertaintySpinBox.setObjectName(u"speechCertaintySpinBox")
        self.speechCertaintySpinBox.setFont(font1)
        self.speechCertaintySpinBox.setAlignment(Qt.AlignCenter)
        self.speechCertaintySpinBox.setMinimum(1)
        self.speechCertaintySpinBox.setMaximum(100)
        self.speechCertaintySpinBox.setValue(38)

        self.gridLayout_5.addWidget(self.speechCertaintySpinBox, 0, 1, 1, 1)

        self.label_4 = QLabel(self.groupBox)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setFont(font1)

        self.gridLayout_5.addWidget(self.label_4, 1, 0, 1, 1)

        self.faceDetectionCertaintySpinBox = QSpinBox(self.groupBox)
        self.faceDetectionCertaintySpinBox.setObjectName(u"faceDetectionCertaintySpinBox")
        self.faceDetectionCertaintySpinBox.setFont(font1)
        self.faceDetectionCertaintySpinBox.setAlignment(Qt.AlignCenter)
        self.faceDetectionCertaintySpinBox.setMinimum(1)
        self.faceDetectionCertaintySpinBox.setMaximum(100)
        self.faceDetectionCertaintySpinBox.setValue(50)

        self.gridLayout_5.addWidget(self.faceDetectionCertaintySpinBox, 1, 1, 1, 1)


        self.gridLayout_6.addLayout(self.gridLayout_5, 0, 0, 1, 1)


        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 2)

        self.label_3 = QLabel(self.dockWidgetContents_6)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setEnabled(False)

        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)

        self.verticalSpacer = QSpacerItem(20, 40, QSizePolicy.Minimum, QSizePolicy.Expanding)

        self.gridLayout.addItem(self.verticalSpacer, 3, 1, 1, 1)

        self.line_2 = QFrame(self.dockWidgetContents_6)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setFrameShape(QFrame.HLine)
        self.line_2.setFrameShadow(QFrame.Sunken)

        self.gridLayout.addWidget(self.line_2, 1, 0, 1, 2)


        self.gridLayout_4.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.settingsDockWidget.setWidget(self.dockWidgetContents_6)
        DialogGUI.addDockWidget(Qt.RightDockWidgetArea, self.settingsDockWidget)

        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuEdit.menuAction())
        self.menuBar.addAction(self.menuRobot.menuAction())
        self.menuBar.addAction(self.menuDatabase.menuAction())
        self.menuBar.addAction(self.menuView.menuAction())
        self.menuFile.addAction(self.actionMenuNew)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionMenuImportBlocks)
        self.menuFile.addAction(self.actionMenuExportBlocks)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionMenuSave)
        self.menuFile.addAction(self.actionMenuSaveAs)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionMenuMusic)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionMenuExit)
        self.menuEdit.addAction(self.actionMenuUndo)
        self.menuEdit.addAction(self.actionMenuRedo)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionMenuCopy)
        self.menuEdit.addAction(self.actionMenuPaste)
        self.menuEdit.addAction(self.actionMenuPasteParameters)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionMenuDelete)
        self.menuEdit.addAction(self.actionMenuClear)
        self.menuRobot.addAction(self.actionMenuConnect)
        self.menuRobot.addAction(self.actionMenuDisconnect)
        self.menuRobot.addSeparator()
        self.menuRobot.addAction(self.actionMenuWakeUp)
        self.menuRobot.addAction(self.actionMenuRest)
        self.menuRobot.addSeparator()
        self.menuRobot.addAction(self.actionMenuEnableTouch)
        self.menuRobot.addAction(self.actionMenuShowImage)
        self.menuRobot.addAction(self.actionMenuHideImage)
        self.menuRobot.addSeparator()
        self.menuRobot.addAction(self.actionMenuVolumeUp)
        self.menuRobot.addAction(self.actionMenuVolumeDown)
        self.menuRobot.addSeparator()
        self.menuRobot.addAction(self.actionMenuTest)
        self.menuRobot.addSeparator()
        self.menuRobot.addAction(self.actionMenuPlay)
        self.menuRobot.addAction(self.actionMenuPause)
        self.menuRobot.addAction(self.actionMenuStop)
        self.menuRobot.addSeparator()
        self.menuRobot.addAction(self.actionMenuSimulate)
        self.menuRobot.addSeparator()
        self.menuRobot.addAction(self.actionMenuEnableMoving)
        self.menuRobot.addAction(self.actionMenuDisableMoving)
        self.menuDatabase.addAction(self.actionMenuDatabaseConnect)
        self.menuDatabase.addAction(self.actionMenuDatabaseDisconnect)
        self.menuView.addAction(self.actionMenuBlockList)
        self.menuView.addAction(self.actionMenuLogs)
        self.menuView.addAction(self.actionMenuSimulationDockView)
        self.menuView.addAction(self.actionMenuMusicDockView)
        self.menuView.addAction(self.actionMenuSettingsDockView)
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionMenuZoomIn)
        self.menuView.addAction(self.actionMenuZoomOut)
        self.mainToolBar.addAction(self.actionMenuSave)
        self.mainToolBar.addSeparator()
        self.mainToolBar.addAction(self.actionMenuCopy)
        self.mainToolBar.addAction(self.actionMenuPasteParameters)
        self.mainToolBar.addSeparator()
        self.mainToolBar.addAction(self.actionMenuClear)
        self.mainToolBar.addSeparator()
        self.mainToolBar.addAction(self.actionMenuConnect)
        self.mainToolBar.addAction(self.actionMenuDisconnect)
        self.mainToolBar.addSeparator()
        self.mainToolBar.addAction(self.actionMenuWakeUp)
        self.mainToolBar.addAction(self.actionMenuRest)
        self.mainToolBar.addSeparator()
        self.mainToolBar.addAction(self.actionMenuVolumeDown)
        self.mainToolBar.addAction(self.actionMenuVolumeUp)
        self.mainToolBar.addSeparator()
        self.mainToolBar.addAction(self.actionMenuPlay)
        self.mainToolBar.addAction(self.actionMenuStop)
        self.mainToolBar.addSeparator()
        self.mainToolBar.addAction(self.actionMenuMusic)
        self.mainToolBar.addSeparator()
        self.mainToolBar.addAction(self.actionMenuSimulate)
        self.mainToolBar.addSeparator()
        self.mainToolBar.addAction(self.actionMenuImportBlocks)
        self.mainToolBar.addAction(self.actionMenuExportBlocks)

        self.retranslateUi(DialogGUI)

        QMetaObject.connectSlotsByName(DialogGUI)
    # setupUi

    def retranslateUi(self, DialogGUI):
        DialogGUI.setWindowTitle(QCoreApplication.translate("DialogGUI", u"Interaction Design", None))
        self.actionReload.setText(QCoreApplication.translate("DialogGUI", u"Reload", None))
#if QT_CONFIG(tooltip)
        self.actionReload.setToolTip(QCoreApplication.translate("DialogGUI", u"Reload", None))
#endif // QT_CONFIG(tooltip)
        self.actionMenuNew.setText(QCoreApplication.translate("DialogGUI", u"New", None))
#if QT_CONFIG(shortcut)
        self.actionMenuNew.setShortcut(QCoreApplication.translate("DialogGUI", u"Ctrl+N", None))
#endif // QT_CONFIG(shortcut)
        self.actionMenuImportBlocks.setText(QCoreApplication.translate("DialogGUI", u"Import Design", None))
#if QT_CONFIG(tooltip)
        self.actionMenuImportBlocks.setToolTip(QCoreApplication.translate("DialogGUI", u"Import Design", None))
#endif // QT_CONFIG(tooltip)
        self.actionMenuExportBlocks.setText(QCoreApplication.translate("DialogGUI", u"Export Design", None))
#if QT_CONFIG(tooltip)
        self.actionMenuExportBlocks.setToolTip(QCoreApplication.translate("DialogGUI", u"Export Design", None))
#endif // QT_CONFIG(tooltip)
        self.actionMenuSave.setText(QCoreApplication.translate("DialogGUI", u"Save", None))
#if QT_CONFIG(shortcut)
        self.actionMenuSave.setShortcut(QCoreApplication.translate("DialogGUI", u"Ctrl+S", None))
#endif // QT_CONFIG(shortcut)
        self.actionMenuSaveAs.setText(QCoreApplication.translate("DialogGUI", u"Save As", None))
#if QT_CONFIG(shortcut)
        self.actionMenuSaveAs.setShortcut(QCoreApplication.translate("DialogGUI", u"Ctrl+Shift+S", None))
#endif // QT_CONFIG(shortcut)
        self.actionMenuExit.setText(QCoreApplication.translate("DialogGUI", u"Exit", None))
#if QT_CONFIG(shortcut)
        self.actionMenuExit.setShortcut(QCoreApplication.translate("DialogGUI", u"Ctrl+Q", None))
#endif // QT_CONFIG(shortcut)
        self.actionMenuUndo.setText(QCoreApplication.translate("DialogGUI", u"Undo", None))
#if QT_CONFIG(shortcut)
        self.actionMenuUndo.setShortcut(QCoreApplication.translate("DialogGUI", u"Ctrl+Z", None))
#endif // QT_CONFIG(shortcut)
        self.actionMenuRedo.setText(QCoreApplication.translate("DialogGUI", u"Redo", None))
#if QT_CONFIG(shortcut)
        self.actionMenuRedo.setShortcut(QCoreApplication.translate("DialogGUI", u"Ctrl+Shift+Z", None))
#endif // QT_CONFIG(shortcut)
        self.actionMenuCopy.setText(QCoreApplication.translate("DialogGUI", u"Copy", None))
#if QT_CONFIG(shortcut)
        self.actionMenuCopy.setShortcut(QCoreApplication.translate("DialogGUI", u"Ctrl+C", None))
#endif // QT_CONFIG(shortcut)
        self.actionMenuPaste.setText(QCoreApplication.translate("DialogGUI", u"Paste", None))
#if QT_CONFIG(shortcut)
        self.actionMenuPaste.setShortcut(QCoreApplication.translate("DialogGUI", u"Ctrl+V", None))
#endif // QT_CONFIG(shortcut)
        self.actionMenuPasteParameters.setText(QCoreApplication.translate("DialogGUI", u"Paste Parameters", None))
#if QT_CONFIG(tooltip)
        self.actionMenuPasteParameters.setToolTip(QCoreApplication.translate("DialogGUI", u"Paste Parameters", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionMenuPasteParameters.setShortcut(QCoreApplication.translate("DialogGUI", u"Ctrl+Shift+V", None))
#endif // QT_CONFIG(shortcut)
        self.actionMenuDelete.setText(QCoreApplication.translate("DialogGUI", u"Delete", None))
#if QT_CONFIG(shortcut)
        self.actionMenuDelete.setShortcut(QCoreApplication.translate("DialogGUI", u"Backspace", None))
#endif // QT_CONFIG(shortcut)
        self.actionMenuClear.setText(QCoreApplication.translate("DialogGUI", u"Clear", None))
#if QT_CONFIG(shortcut)
        self.actionMenuClear.setShortcut(QCoreApplication.translate("DialogGUI", u"Ctrl+Shift+Backspace", None))
#endif // QT_CONFIG(shortcut)
        self.actionMenuConnect.setText(QCoreApplication.translate("DialogGUI", u"Connect", None))
        self.actionMenuDisconnect.setText(QCoreApplication.translate("DialogGUI", u"Disconnect", None))
        self.actionMenuWakeUp.setText(QCoreApplication.translate("DialogGUI", u"Wake Up", None))
        self.actionMenuRest.setText(QCoreApplication.translate("DialogGUI", u"Rest", None))
        self.actionMenuEnableTouch.setText(QCoreApplication.translate("DialogGUI", u"Enable Touch", None))
        self.actionMenuShowImage.setText(QCoreApplication.translate("DialogGUI", u"Show Image", None))
        self.actionMenuHideImage.setText(QCoreApplication.translate("DialogGUI", u"Hide Image", None))
        self.actionMenuVolumeUp.setText(QCoreApplication.translate("DialogGUI", u"Vol+", None))
        self.actionMenuVolumeDown.setText(QCoreApplication.translate("DialogGUI", u"Vol-", None))
        self.actionMenuTest.setText(QCoreApplication.translate("DialogGUI", u"Test", None))
        self.actionMenuPlay.setText(QCoreApplication.translate("DialogGUI", u"Play", None))
        self.actionMenuPause.setText(QCoreApplication.translate("DialogGUI", u"Pause", None))
        self.actionMenuStop.setText(QCoreApplication.translate("DialogGUI", u"Stop", None))
        self.actionMenuEnableMoving.setText(QCoreApplication.translate("DialogGUI", u"Enable Moving", None))
        self.actionMenuDisableMoving.setText(QCoreApplication.translate("DialogGUI", u"Disable Moving", None))
        self.actionMenuDatabaseConnect.setText(QCoreApplication.translate("DialogGUI", u"Connect", None))
        self.actionMenuDatabaseDisconnect.setText(QCoreApplication.translate("DialogGUI", u"Disconnect", None))
        self.actionMenuZoomIn.setText(QCoreApplication.translate("DialogGUI", u"Zoom In", None))
#if QT_CONFIG(shortcut)
        self.actionMenuZoomIn.setShortcut(QCoreApplication.translate("DialogGUI", u"Ctrl+=", None))
#endif // QT_CONFIG(shortcut)
        self.actionMenuZoomOut.setText(QCoreApplication.translate("DialogGUI", u"Zoom Out", None))
#if QT_CONFIG(tooltip)
        self.actionMenuZoomOut.setToolTip(QCoreApplication.translate("DialogGUI", u"Zoom Out", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionMenuZoomOut.setShortcut(QCoreApplication.translate("DialogGUI", u"Ctrl+-", None))
#endif // QT_CONFIG(shortcut)
        self.actionMenuBlockList.setText(QCoreApplication.translate("DialogGUI", u"Block List Panel", None))
        self.actionMenuLogs.setText(QCoreApplication.translate("DialogGUI", u"Logs Panel", None))
        self.actionMenuSimulate.setText(QCoreApplication.translate("DialogGUI", u"Simulate", None))
        self.actionMenuMusic.setText(QCoreApplication.translate("DialogGUI", u"Spotify", None))
#if QT_CONFIG(tooltip)
        self.actionMenuMusic.setToolTip(QCoreApplication.translate("DialogGUI", u"Music", None))
#endif // QT_CONFIG(tooltip)
        self.actionMenuMusicDockView.setText(QCoreApplication.translate("DialogGUI", u"Music Panel", None))
        self.actionMenuSimulationDockView.setText(QCoreApplication.translate("DialogGUI", u"Simulation Panel", None))
#if QT_CONFIG(tooltip)
        self.actionMenuSimulationDockView.setToolTip(QCoreApplication.translate("DialogGUI", u"Simulation", None))
#endif // QT_CONFIG(tooltip)
        self.actionMenuSettingsDockView.setText(QCoreApplication.translate("DialogGUI", u"Settings Panel", None))
        self.label_8.setText(QCoreApplication.translate("DialogGUI", u"DESIGN PANEL", None))
        self.menuFile.setTitle(QCoreApplication.translate("DialogGUI", u"File", None))
        self.menuEdit.setTitle(QCoreApplication.translate("DialogGUI", u"Edit", None))
        self.menuRobot.setTitle(QCoreApplication.translate("DialogGUI", u"Robot", None))
        self.menuDatabase.setTitle(QCoreApplication.translate("DialogGUI", u"Database", None))
        self.menuView.setTitle(QCoreApplication.translate("DialogGUI", u"View", None))
        self.blocksDockWidget.setWindowTitle(QCoreApplication.translate("DialogGUI", u"Dialogue Blocks", None))
        self.groupBox_11.setTitle("")
        self.dialogueBlocksCategoryComboBox.setItemText(0, QCoreApplication.translate("DialogGUI", u"All", None))
        self.dialogueBlocksCategoryComboBox.setItemText(1, QCoreApplication.translate("DialogGUI", u"Opening", None))
        self.dialogueBlocksCategoryComboBox.setItemText(2, QCoreApplication.translate("DialogGUI", u"Service-Provision", None))
        self.dialogueBlocksCategoryComboBox.setItemText(3, QCoreApplication.translate("DialogGUI", u"Closing", None))
        self.dialogueBlocksCategoryComboBox.setItemText(4, QCoreApplication.translate("DialogGUI", u"Chit-Chat", None))


        __sortingEnabled = self.dragListWidget.isSortingEnabled()
        self.dragListWidget.setSortingEnabled(False)
        ___qlistwidgetitem = self.dragListWidget.item(0)
        ___qlistwidgetitem.setText(QCoreApplication.translate("DialogGUI", u"Salutation", None));
        self.dragListWidget.setSortingEnabled(__sortingEnabled)

        self.logsDockWidget.setWindowTitle(QCoreApplication.translate("DialogGUI", u"Logs", None))
        self.musicDockWidget.setWindowTitle(QCoreApplication.translate("DialogGUI", u"Music Player", None))
        self.label.setText(QCoreApplication.translate("DialogGUI", u"Playlists", None))
        self.label_5.setText(QCoreApplication.translate("DialogGUI", u"Tracks", None))
        self.musicPauseButton.setText(QCoreApplication.translate("DialogGUI", u"Pause", None))
        self.musicPlayButton.setText(QCoreApplication.translate("DialogGUI", u"Play", None))
        self.musicMessageLineEdit.setText("")
        self.musicVolumeButton.setText(QCoreApplication.translate("DialogGUI", u"Vol (%)", None))
        self.settingsDockWidget.setWindowTitle(QCoreApplication.translate("DialogGUI", u"Settings", None))
        self.groupBox.setTitle(QCoreApplication.translate("DialogGUI", u"Certainty (%)", None))
        self.label_2.setText(QCoreApplication.translate("DialogGUI", u"Speech-Recognition", None))
        self.label_4.setText(QCoreApplication.translate("DialogGUI", u"Face-Detection", None))
        self.label_3.setText(QCoreApplication.translate("DialogGUI", u"Delay Between Blocks (s)", None))
    # retranslateUi

