# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interaction_manager/ui/spotifydialog.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SpotifyDialog(object):
    def setupUi(self, SpotifyDialog):
        SpotifyDialog.setObjectName("SpotifyDialog")
        SpotifyDialog.resize(424, 564)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(SpotifyDialog.sizePolicy().hasHeightForWidth())
        SpotifyDialog.setSizePolicy(sizePolicy)
        SpotifyDialog.setMinimumSize(QtCore.QSize(0, 0))
        SpotifyDialog.setMaximumSize(QtCore.QSize(750, 1000))
        self.gridLayout_5 = QtWidgets.QGridLayout(SpotifyDialog)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem, 6, 0, 1, 1)
        self.defaultSettingsCheckBox = QtWidgets.QCheckBox(SpotifyDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.defaultSettingsCheckBox.sizePolicy().hasHeightForWidth())
        self.defaultSettingsCheckBox.setSizePolicy(sizePolicy)
        self.defaultSettingsCheckBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.defaultSettingsCheckBox.setChecked(True)
        self.defaultSettingsCheckBox.setObjectName("defaultSettingsCheckBox")
        self.gridLayout_3.addWidget(self.defaultSettingsCheckBox, 1, 0, 1, 1)
        self.connectButton = QtWidgets.QPushButton(SpotifyDialog)
        self.connectButton.setObjectName("connectButton")
        self.gridLayout_3.addWidget(self.connectButton, 1, 1, 1, 1)
        self.settingsGroupBox = QtWidgets.QGroupBox(SpotifyDialog)
        self.settingsGroupBox.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setBold(True)
        font.setWeight(75)
        self.settingsGroupBox.setFont(font)
        self.settingsGroupBox.setObjectName("settingsGroupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.settingsGroupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_12 = QtWidgets.QGridLayout()
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.label_3 = QtWidgets.QLabel(self.settingsGroupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout_12.addWidget(self.label_3, 1, 0, 1, 1)
        self.usernameLineEdit = QtWidgets.QLineEdit(self.settingsGroupBox)
        self.usernameLineEdit.setObjectName("usernameLineEdit")
        self.gridLayout_12.addWidget(self.usernameLineEdit, 0, 1, 1, 2)
        self.label_4 = QtWidgets.QLabel(self.settingsGroupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout_12.addWidget(self.label_4, 0, 0, 1, 1)
        self.redirectURILineEdit = QtWidgets.QLineEdit(self.settingsGroupBox)
        self.redirectURILineEdit.setObjectName("redirectURILineEdit")
        self.gridLayout_12.addWidget(self.redirectURILineEdit, 3, 1, 1, 2)
        self.clientSecretLineEdit = QtWidgets.QLineEdit(self.settingsGroupBox)
        self.clientSecretLineEdit.setObjectName("clientSecretLineEdit")
        self.gridLayout_12.addWidget(self.clientSecretLineEdit, 2, 1, 1, 2)
        self.label_2 = QtWidgets.QLabel(self.settingsGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.gridLayout_12.addWidget(self.label_2, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.settingsGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.gridLayout_12.addWidget(self.label, 3, 0, 1, 1)
        self.clientIDLineEdit = QtWidgets.QLineEdit(self.settingsGroupBox)
        self.clientIDLineEdit.setObjectName("clientIDLineEdit")
        self.gridLayout_12.addWidget(self.clientIDLineEdit, 1, 1, 1, 2)
        self.gridLayout.addLayout(self.gridLayout_12, 0, 1, 1, 1)
        self.gridLayout_3.addWidget(self.settingsGroupBox, 0, 0, 1, 2)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.playButton = QtWidgets.QPushButton(SpotifyDialog)
        self.playButton.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.playButton.sizePolicy().hasHeightForWidth())
        self.playButton.setSizePolicy(sizePolicy)
        self.playButton.setObjectName("playButton")
        self.gridLayout_4.addWidget(self.playButton, 3, 2, 1, 1)
        self.playlistComboBox = QtWidgets.QComboBox(SpotifyDialog)
        self.playlistComboBox.setObjectName("playlistComboBox")
        self.gridLayout_4.addWidget(self.playlistComboBox, 1, 1, 1, 2)
        self.line_2 = QtWidgets.QFrame(SpotifyDialog)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_4.addWidget(self.line_2, 0, 0, 1, 3)
        self.label_5 = QtWidgets.QLabel(SpotifyDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 1, 0, 1, 1)
        self.trackComboBox = QtWidgets.QComboBox(SpotifyDialog)
        self.trackComboBox.setObjectName("trackComboBox")
        self.gridLayout_4.addWidget(self.trackComboBox, 2, 1, 1, 2)
        self.label_6 = QtWidgets.QLabel(SpotifyDialog)
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 2, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_4, 2, 0, 1, 2)
        self.groupBox_2 = QtWidgets.QGroupBox(SpotifyDialog)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.messageTextEdit = QtWidgets.QTextEdit(self.groupBox_2)
        self.messageTextEdit.setAutoFillBackground(True)
        self.messageTextEdit.setStyleSheet("background: rgb(76, 76, 76)")
        self.messageTextEdit.setReadOnly(True)
        self.messageTextEdit.setObjectName("messageTextEdit")
        self.gridLayout_2.addWidget(self.messageTextEdit, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_2, 4, 0, 1, 2)
        self.buttonBox = QtWidgets.QDialogButtonBox(SpotifyDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_3.addWidget(self.buttonBox, 5, 0, 1, 2)
        self.line = QtWidgets.QFrame(SpotifyDialog)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_3.addWidget(self.line, 3, 0, 1, 2)
        self.gridLayout_5.addLayout(self.gridLayout_3, 0, 0, 1, 1)

        self.retranslateUi(SpotifyDialog)
        self.buttonBox.accepted.connect(SpotifyDialog.accept)
        self.buttonBox.rejected.connect(SpotifyDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(SpotifyDialog)
        SpotifyDialog.setTabOrder(self.usernameLineEdit, self.clientIDLineEdit)
        SpotifyDialog.setTabOrder(self.clientIDLineEdit, self.clientSecretLineEdit)
        SpotifyDialog.setTabOrder(self.clientSecretLineEdit, self.redirectURILineEdit)
        SpotifyDialog.setTabOrder(self.redirectURILineEdit, self.defaultSettingsCheckBox)
        SpotifyDialog.setTabOrder(self.defaultSettingsCheckBox, self.connectButton)
        SpotifyDialog.setTabOrder(self.connectButton, self.playlistComboBox)
        SpotifyDialog.setTabOrder(self.playlistComboBox, self.trackComboBox)
        SpotifyDialog.setTabOrder(self.trackComboBox, self.playButton)
        SpotifyDialog.setTabOrder(self.playButton, self.messageTextEdit)

    def retranslateUi(self, SpotifyDialog):
        _translate = QtCore.QCoreApplication.translate
        SpotifyDialog.setWindowTitle(_translate("SpotifyDialog", "Spotify"))
        self.defaultSettingsCheckBox.setText(_translate("SpotifyDialog", "Default Settings"))
        self.connectButton.setText(_translate("SpotifyDialog", "Connect"))
        self.settingsGroupBox.setTitle(_translate("SpotifyDialog", "Spotify Settings"))
        self.label_3.setText(_translate("SpotifyDialog", "Client ID"))
        self.label_4.setText(_translate("SpotifyDialog", "Username"))
        self.redirectURILineEdit.setPlaceholderText(_translate("SpotifyDialog", "http://localhost/8080/"))
        self.label_2.setText(_translate("SpotifyDialog", "Client Secret"))
        self.label.setText(_translate("SpotifyDialog", "Redirect URI"))
        self.playButton.setText(_translate("SpotifyDialog", "Test"))
        self.label_5.setText(_translate("SpotifyDialog", "Playlists"))
        self.label_6.setText(_translate("SpotifyDialog", "Tracks"))
        self.groupBox_2.setTitle(_translate("SpotifyDialog", "Log"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SpotifyDialog = QtWidgets.QDialog()
    ui = Ui_SpotifyDialog()
    ui.setupUi(SpotifyDialog)
    SpotifyDialog.show()
    sys.exit(app.exec_())
