tags:
  askQuestionTag:
    pages:
      - index
      - displayinfo
      - displayimage
  confirmationTag:
    pages:
      - index
      - displayinfo
      - displayimage
      - confirmation
  offerHelpTag:
    pages:
      - index
      - displayinfo
      - help